### ISSUE TITLE
End of Nvidia Gamestream -> Sunshine?

### ISSUE THREAD

**Issue by thomasfjen** [Rantunah/moonlight-toggler#1]
As you probably know the Nvidia Gamestream solution is coming to an end. Is there a way you could integrate the sunshine streaming solution? As additional benefit you would open the solution to other graphics cards manufacturers. 

Thank you anyway to making this nice tool!

**Comment by Rantunah** [comment]
Hey, thanks for reaching out.
I've just made the switch to Sunshine this week so I might be looking into changing the script to set up monitor switching automatically.

I'll give you some quick pointers on how to do it manually though, it's actually way simpler than GameStream.

So, Sunshine lets you set up a command to call when you start streaming an application and another when you stop streaming.
- go to `https://localhost:47990/apps`;
- pick an application and press `Edit`;
- There's an option to write a command in a `Do` field and in an `Undo` field:
    • in the `Do` field, write the command that switches to your `remote` profile.
    Assuming you've set up `moonlight-toggler` before:
    ```powershel
    <full_path_to_moonlighttoggler>\moonlight-toggler\bin\MonitorSwitcher.exe -load:<full_path_to_moonlighttoggler>\moonlight-toggler\profiles\remote.xml
    ```
    • in the `Undo` field, write the command that switches to your `monitor` profile.
    ```powershel
    <full_path_to_moonlighttoggler>\moonlight-toggler\bin\MonitorSwitcher.exe -load:<full_path_to_moonlighttoggler>\moonlight-toggler\profiles\monitor.xml
    ```
    ![image](https://user-images.githubusercontent.com/90865007/224184674-653cdde3-1149-4f4d-abac-e4b1a7b06c6a.png)
    • don't press the `+Add` button unless you want to add another command and press the `Save` button at the end of the page.

And that's it! After Sunshine restarts, the next time you start the application in Moonlight, your `remote` switch should fire automatically. No server process needed.
The only caveat is that if you shut down your PC while streaming, the `Undo` command won't fire and you'll still be on the `remote` profile.

**Comment by thomasfjen** [comment]
Funny enough that's exactly how i have done it in the mean time while searching for solution. 
Only caveat i have is similar to your mentioned problem when shutting down the PC but that's in combination with Moonlight started through SteamOS not closing the moonlight game stream correctly and staying on the remote profile. 
But i think that's another topic and independent to your tool and moonlight

Thanks!

**Comment by voidxO7** [comment]
Hey man! I think this is really cool, do you think you would ever update it in the future?

**Comment by Rantunah** [comment]
@voidxO7 I've been neglecting to mark this repository as "deprecated" for a while now. 
Nvidia has ceased support for Gamestream and I moved to a place that allowed me some desk space for my PC, so, even if I were to continue development for Sunshine, I'd have no way to test the changes I've made.
This was a short lived script, but I'm glad it was helpful to you and others.
